import type {
  Activity,
  Asset,
  ContextLayer,
  Gate,
  PromptRevision,
  ProviderCapability,
  ProviderJob,
  Shot,
  StudioState,
  ViewId,
} from "./domain";

const hash = (seed: string) =>
  Array.from({ length: 64 }, (_, index) => ((seed.charCodeAt(index % seed.length) + index) % 16).toString(16)).join("");

const binding = (objectType: string, revisionId: string, label: string) => ({
  objectType,
  revisionId,
  contentHash: hash(revisionId),
  label,
});

export const capabilities: ProviderCapability[] = [
  {
    alias: "text.primary",
    liveConfigured: false,
    liveCallsEnabled: false,
    dryRunAvailable: true,
    mockAvailable: true,
    defaultProvider: "volcengine_ark",
    liveEvidence: "not_configured",
    mockEvidence: "mock_only",
  },
  {
    alias: "image.primary",
    liveConfigured: false,
    liveCallsEnabled: false,
    dryRunAvailable: true,
    mockAvailable: true,
    defaultProvider: "volcengine_ark",
    liveEvidence: "not_configured",
    mockEvidence: "mock_only",
  },
  {
    alias: "video.primary",
    liveConfigured: false,
    liveCallsEnabled: false,
    dryRunAvailable: true,
    mockAvailable: true,
    defaultProvider: "volcengine_ark",
    liveEvidence: "not_configured",
    mockEvidence: "mock_only",
  },
  {
    alias: "speech.primary",
    liveConfigured: false,
    liveCallsEnabled: false,
    dryRunAvailable: true,
    mockAvailable: true,
    defaultProvider: "volcengine_speech",
    liveEvidence: "not_configured",
    mockEvidence: "mock_only",
  },
];

const g1Bindings = [
  binding("WORLD", "world-r7-9b7d", "世界观 · 潮汐城"),
  binding("CHARACTER_SET", "chars-r4-c6e3", "角色设定 · 6 人"),
  binding("ASSET_SET", "assets-r12-a2d9", "基础原画 · 14 项"),
];
const g2Bindings = [
  binding("EPISODE_SCRIPT", "script-e03-r6", "第 03 集剧本 · r6"),
  binding("STORYBOARD", "boards-e03-r9", "分镜脚本 · 5 镜"),
  binding("PROMPT_SET", "prompts-e03-r3", "Prompt 快照 · r3"),
];
const g3Bindings = [
  binding("EPISODE_REVISION", "episode-e03-r2", "第 03 集 · revision r2"),
  binding("EPISODE_CUT", "cut-e03-r2", "第 03 集成片 · r2"),
  binding("SUBTITLE", "sub-e03-r3", "中文字幕 · r3"),
  binding("QC_REPORT", "qc-e03-r2", "画面 / 字幕 / 音轨 QC · passed"),
  binding("MANIFEST", "manifest-e03-r1", "谱系清单 · r1"),
  binding("ARTIFACT", "artifact-cut-e03-r2", "成片 artifact commit · r2"),
];

export const gates: Record<"G1" | "G2" | "G3", Gate> = {
  G1: {
    id: "G1",
    eyebrow: "第一道闸门",
    title: "内容与资产",
    description: "确认世界观、角色、场景、道具和权利凭据，再允许剧本引用。",
    state: "PENDING",
    etag: 7,
    revision: 7,
    revisionId: "gate-g1-r7",
    bindings: g1Bindings,
    history: [
      {
        revision: 6,
        revisionId: "gate-g1-r6",
        state: "SUPERSEDED",
        author: "美术 Agent",
        createdAt: "07-29 20:14",
        note: "补充季岚雨衣背面与灯塔值班室",
      },
      {
        revision: 7,
        revisionId: "gate-g1-r7",
        state: "CURRENT",
        author: "创作编排",
        createdAt: "07-30 09:20",
        note: "校验 14 项资产引用和权利快照",
      },
    ],
  },
  G2: {
    id: "G2",
    eyebrow: "第二道闸门",
    title: "剧本与分镜",
    description: "锁定本集剧本、镜头节奏、上下文快照与待生成 Prompt。",
    state: "BLOCKED",
    etag: 9,
    revision: 9,
    revisionId: "gate-g2-r9",
    bindings: g2Bindings,
    history: [
      {
        revision: 8,
        revisionId: "gate-g2-r8",
        state: "RETURNED",
        author: "导演",
        createdAt: "07-29 22:40",
        note: "第三镜情绪跨越过快",
      },
      {
        revision: 9,
        revisionId: "gate-g2-r9",
        state: "CURRENT",
        author: "编剧 Agent",
        createdAt: "07-30 09:36",
        note: "增加无对白停顿，拆分最后一个长镜头",
      },
    ],
  },
  G3: {
    id: "G3",
    eyebrow: "第三道闸门",
    title: "成片锁版",
    description: "逐镜确认画面、字幕、声音、AI 标识与最终谱系清单。",
    state: "BLOCKED",
    etag: 2,
    revision: 2,
    revisionId: "gate-g3-r2",
    bindings: g3Bindings,
    history: [
      {
        revision: 1,
        revisionId: "gate-g3-r1",
        state: "RETURNED",
        author: "制片",
        createdAt: "07-30 08:52",
        note: "S03 字幕提前 6 帧",
      },
      {
        revision: 2,
        revisionId: "gate-g3-r2",
        state: "CURRENT",
        author: "后期 Agent",
        createdAt: "07-30 09:48",
        note: "修正 S03 字幕并重建成片 Manifest",
      },
    ],
  },
};

export const assets: Asset[] = [
  {
    id: "asset-jilan",
    kind: "CHARACTER",
    name: "季岚",
    subtitle: "潮汐观测员 · 三视图 / 8 表情",
    palette: ["#2f5965", "#d8a661", "#d9d5c8"],
    version: 4,
    revisionId: "asset-jilan-r4",
    state: "APPROVED",
    usages: 18,
    rights: "cleared",
    revisions: [
      { version: 2, revisionId: "asset-jilan-r2", state: "APPROVED", createdAt: "07-27", note: "首次 G1 锁定" },
      { version: 3, revisionId: "asset-jilan-r3", state: "STALE", createdAt: "07-28", note: "雨衣色温偏暖" },
      { version: 4, revisionId: "asset-jilan-r4", state: "DRAFT", createdAt: "07-30", note: "增加湿发状态" },
    ],
  },
  {
    id: "asset-hejin",
    kind: "CHARACTER",
    name: "何津",
    subtitle: "旧港维修师 · 三视图 / 6 表情",
    palette: ["#4b4338", "#94846e", "#cfc8b8"],
    version: 3,
    revisionId: "asset-hejin-r3",
    state: "APPROVED",
    usages: 11,
    rights: "cleared",
    revisions: [
      { version: 2, revisionId: "asset-hejin-r2", state: "APPROVED", createdAt: "07-27", note: "G1 锁定" },
      { version: 3, revisionId: "asset-hejin-r3", state: "DRAFT", createdAt: "07-30", note: "工作服油渍状态" },
    ],
  },
  {
    id: "asset-lighthouse",
    kind: "LOCATION",
    name: "北岬灯塔",
    subtitle: "雨夜 / 退潮 / 停电三种状态",
    palette: ["#102c36", "#7b8e8e", "#e6b35d"],
    version: 5,
    revisionId: "asset-lighthouse-r5",
    state: "APPROVED",
    usages: 24,
    rights: "cleared",
    revisions: [
      { version: 4, revisionId: "asset-lighthouse-r4", state: "APPROVED", createdAt: "07-28", note: "G1 锁定" },
      { version: 5, revisionId: "asset-lighthouse-r5", state: "DRAFT", createdAt: "07-30", note: "增加低潮滩涂" },
    ],
  },
  {
    id: "asset-tideclock",
    kind: "PROP",
    name: "潮汐钟",
    subtitle: "核心道具 · 铜制 / 断针状态",
    palette: ["#8b5c36", "#d4b16f", "#1c2528"],
    version: 2,
    revisionId: "asset-tideclock-r2",
    state: "APPROVED",
    usages: 9,
    rights: "review",
    revisions: [
      { version: 1, revisionId: "asset-tideclock-r1", state: "APPROVED", createdAt: "07-27", note: "初版道具设定" },
      { version: 2, revisionId: "asset-tideclock-r2", state: "DRAFT", createdAt: "07-30", note: "补充断针特写" },
    ],
  },
  {
    id: "asset-radio",
    kind: "PROP",
    name: "短波电台",
    subtitle: "旧港制式 · 水渍 / 工作状态",
    palette: ["#2e3b37", "#66736b", "#c07747"],
    version: 3,
    revisionId: "asset-radio-r3",
    state: "DRAFT",
    usages: 6,
    rights: "cleared",
    revisions: [
      { version: 2, revisionId: "asset-radio-r2", state: "APPROVED", createdAt: "07-28", note: "G1 锁定" },
      { version: 3, revisionId: "asset-radio-r3", state: "DRAFT", createdAt: "07-30", note: "新增水渍状态" },
    ],
  },
];

export const shots: Shot[] = [
  {
    id: "shot-031",
    code: "S03-01",
    title: "风暴前的灯塔",
    duration: 4,
    camera: "24mm 广角 · 缓慢推进",
    action: "灯塔切开横雨，季岚逆风走上堤岸。",
    assetIds: ["asset-jilan", "asset-lighthouse"],
    promptRevision: 3,
    contextHash: hash("shot-031-context"),
    state: "READY",
  },
  {
    id: "shot-032",
    code: "S03-02",
    title: "没有回音",
    duration: 5,
    camera: "50mm 中景 · 手持微晃",
    action: "季岚按下发射键，电台只有海潮般的白噪声。",
    dialogue: "何津，你听得到吗？",
    assetIds: ["asset-jilan", "asset-radio"],
    promptRevision: 3,
    contextHash: hash("shot-032-context"),
    state: "READY",
  },
  {
    id: "shot-033",
    code: "S03-03",
    title: "断针回转",
    duration: 4,
    camera: "85mm 特写 · 焦点转移",
    action: "断裂的潮汐钟指针逆向转动，水珠悬停在半空。",
    assetIds: ["asset-tideclock"],
    promptRevision: 4,
    contextHash: hash("shot-033-context"),
    state: "READY",
  },
  {
    id: "shot-034",
    code: "S03-04",
    title: "值班室",
    duration: 5,
    camera: "35mm 双人构图 · 固定",
    action: "门被撞开，何津浑身湿透，二人隔着灯桌对视。",
    dialogue: "不是海在涨，是时间在退。",
    assetIds: ["asset-jilan", "asset-hejin", "asset-lighthouse"],
    promptRevision: 3,
    contextHash: hash("shot-034-context"),
    state: "GENERATING",
  },
  {
    id: "shot-035",
    code: "S03-05",
    title: "熄灯",
    duration: 3,
    camera: "24mm 远景 · 快速拉远",
    action: "灯塔骤然熄灭，远海浮现一圈倒转的城市灯火。",
    assetIds: ["asset-lighthouse"],
    promptRevision: 3,
    contextHash: hash("shot-035-context"),
    state: "SUCCEEDED",
  },
];

const now = "10:02";
export const jobs: ProviderJob[] = [
  {
    id: "job-v-031",
    shot: "S03-01",
    shotId: "shot-031",
    capability: "video.primary",
    provider: "volcengine_ark",
    model: "video.primary / route-v4",
    evidence: "mock_only",
    state: "QUEUED",
    progress: 0,
    retryCount: 0,
    attempt: 1,
    isCurrentAttempt: true,
    traceId: "trc_8fd1e9",
    taskId: "mock-task-031",
    costMicros: 420000,
    costVerified: false,
    updatedAt: now,
  },
  {
    id: "job-v-032",
    shot: "S03-02",
    shotId: "shot-032",
    capability: "video.primary",
    provider: "volcengine_ark",
    model: "video.primary / route-v4",
    evidence: "mock_only",
    state: "RUNNING",
    progress: 64,
    retryCount: 0,
    attempt: 1,
    isCurrentAttempt: true,
    traceId: "trc_54d07c",
    taskId: "mock-task-032",
    costMicros: 520000,
    costVerified: false,
    updatedAt: now,
  },
  {
    id: "job-v-033",
    shot: "S03-03",
    shotId: "shot-033",
    capability: "video.primary",
    provider: "volcengine_ark",
    model: "video.primary / route-v4",
    evidence: "mock_only",
    state: "RETRYING",
    progress: 18,
    retryCount: 1,
    attempt: 2,
    isCurrentAttempt: true,
    traceId: "trc_d8c281",
    taskId: "mock-task-033",
    costMicros: 420000,
    costVerified: false,
    updatedAt: now,
    failure: {
      errorCode: "rate_limited",
      retryable: true,
      requiresAction: false,
      retryAfterSeconds: 24,
      httpStatus: 429,
      suggestedAction: "保留同一 Job ID，按 Retry-After 自动重试。",
    },
  },
  {
    id: "job-v-034",
    shot: "S03-04",
    shotId: "shot-034",
    capability: "video.primary",
    provider: "volcengine_ark",
    model: "video.primary / route-v4",
    evidence: "mock_only",
    state: "REQUIRES_ACTION",
    progress: 0,
    retryCount: 0,
    attempt: 1,
    isCurrentAttempt: true,
    traceId: "trc_1cd203",
    costMicros: 520000,
    costVerified: false,
    updatedAt: "09:58",
    failure: {
      errorCode: "content_blocked",
      retryable: false,
      requiresAction: true,
      httpStatus: 422,
      suggestedAction: "修改 S03-04 的画面描述并创建新的创作 attempt。",
    },
  },
  {
    id: "job-v-035",
    shot: "S03-05",
    shotId: "shot-035",
    capability: "video.primary",
    provider: "volcengine_ark",
    model: "video.primary / route-v4",
    evidence: "mock_only",
    state: "SUCCEEDED",
    progress: 100,
    retryCount: 0,
    attempt: 1,
    isCurrentAttempt: true,
    traceId: "trc_77ef21",
    taskId: "mock-task-035",
    costMicros: 320000,
    costVerified: false,
    updatedAt: "09:56",
  },
];

export const contextLayers: ContextLayer[] = [
  {
    scope: "SERIES",
    label: "剧集 · 潮汐失语者",
    revision: 4,
    revisionId: "ctx-series-r4",
    inherited: true,
    entries: [
      { key: "视觉语法", value: "近未来沿海现实主义；湿冷、克制、非霓虹赛博" },
      { key: "色彩", value: "青灰主调，钠灯琥珀仅作为叙事线索" },
      { key: "摄影", value: "自然镜头呼吸，避免无动机的快速运镜" },
    ],
  },
  {
    scope: "EPISODE",
    label: "单集 · E03 倒流",
    revision: 6,
    revisionId: "ctx-episode-r6",
    inherited: true,
    entries: [
      { key: "情绪弧", value: "怀疑 → 证实 → 失去方向" },
      { key: "天气", value: "台风登陆前 40 分钟，横向雨线" },
      { key: "节奏", value: "留出 1–2 秒无对白反应" },
    ],
  },
  {
    scope: "SCENE",
    label: "场景 · SC-12 北岬灯塔",
    revision: 3,
    revisionId: "ctx-scene-r3",
    inherited: true,
    entries: [
      { key: "主光", value: "旋转灯束每 8 秒扫过一次" },
      { key: "连续性", value: "季岚右肩和发梢持续湿透" },
      { key: "声音", value: "风噪压低对白尾音" },
    ],
  },
  {
    scope: "SHOT",
    label: "镜头 · S03-03 断针回转",
    revision: 2,
    revisionId: "ctx-shot-r2",
    inherited: false,
    entries: [
      { key: "帧率意图", value: "主观慢速，水珠停顿 12 帧", override: true },
      { key: "景深", value: "极浅景深，人物只留为反射", override: true },
    ],
  },
];

export const promptRevisions: PromptRevision[] = [
  {
    version: 2,
    revisionId: "prompt-s033-r2",
    state: "LOCKED",
    createdAt: "07-29 23:18",
    summary: "G2 上一轮锁定版本",
    tokens: 438,
    content:
      "85mm macro close-up of a broken brass tide clock. The snapped hand turns backward while rain beads tremble on the glass. Cold storm ambience, restrained coastal realism.",
    changes: [],
  },
  {
    version: 3,
    revisionId: "prompt-s033-r3",
    state: "SUPERSEDED",
    createdAt: "07-30 08:42",
    summary: "补充镜面人物反射",
    tokens: 472,
    content:
      "85mm macro close-up of a broken brass tide clock. The snapped hand turns backward while rain beads tremble on the glass. Ji Lan appears only as a soft reflection. Cold storm ambience, restrained coastal realism.",
    changes: [
      { type: "add", text: "Ji Lan appears only as a soft reflection." },
    ],
  },
  {
    version: 4,
    revisionId: "prompt-s033-r4",
    state: "CURRENT",
    createdAt: "07-30 09:36",
    summary: "覆盖镜头速度，保持全剧光线继承",
    tokens: 501,
    content:
      "85mm macro close-up of a broken brass tide clock. The snapped hand turns backward while rain beads hold still for twelve frames. Ji Lan appears only as a soft reflection. The amber lighthouse beam crosses once. Cold storm ambience, restrained coastal realism.",
    changes: [
      { type: "remove", text: "rain beads tremble on the glass" },
      { type: "add", text: "rain beads hold still for twelve frames" },
      { type: "add", text: "The amber lighthouse beam crosses once." },
    ],
  },
];

export const activity: Activity[] = [
  { id: "act-1", at: "10:02", actor: "编排器", action: "等待 G1", detail: "G2 和付费任务保持阻断" },
  { id: "act-2", at: "09:58", actor: "Provider Mock", action: "需要处理", detail: "S03-04 content_blocked · trace trc_1cd203" },
  { id: "act-3", at: "09:48", actor: "后期 Agent", action: "创建 revision", detail: "成片 r2 保留 r1，不覆盖历史产物" },
  { id: "act-4", at: "09:36", actor: "编剧 Agent", action: "创建 revision", detail: "分镜 r9 · Prompt r4" },
];

const initialStudioView = (): ViewId => {
  if (import.meta.env.VITE_STUDIO_INITIAL_VIEW === "overview") return "overview";
  if (["local-experience", "live"].includes(import.meta.env.VITE_STUDIO_MODE ?? "")) {
    return "live-shot";
  }
  return "overview";
};

export const createInitialState = (): StudioState => ({
  view: initialStudioView(),
  inspectorOpen: false,
  busy: false,
  project: {
    id: "series-tide-001",
    title: "潮汐失语者",
    episode: "E03",
    episodeTitle: "倒流",
    aspectRatio: "16:9",
    targetDuration: "03:20",
    targetAudience: "16–35 岁悬疑剧观众",
    visualStyle: "近未来沿海现实主义",
    mode: "mock",
  },
  capabilities,
  gates: structuredClone(gates),
  jobs: structuredClone(jobs),
  jobsViewState: "READY",
  assets: structuredClone(assets),
  shots: structuredClone(shots),
  contextLayers: structuredClone(contextLayers),
  promptRevisions: structuredClone(promptRevisions),
  selectedPromptVersion: 4,
  selectedAssetId: "asset-jilan",
  activity: structuredClone(activity),
  toasts: [],
  liveShot: { phase: "DRAFT" },
});
